name: Deploy ab-portfolio to Github Pages

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.1.0

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build
        env:
          VITE_F_API_KEY: ${{ secrets.VITE_F_API_KEY }}
          VITE_F_AUTH_DOMAIN: ${{ secrets.VITE_F_AUTH_DOMAIN }}
          VITE_F_PROJECT_ID: ${{ secrets.VITE_F_PROJECT_ID }}
          VITE_F_STORAGE_BUCKET: ${{ secrets.VITE_F_STORAGE_BUCKET }}
          VITE_F_MESSAGE_SENDER_ID: ${{ secrets.VITE_F_MESSAGE_SENDER_ID }}
          VITE_F_APP_ID: ${{ secrets.VITE_F_APP_ID }}
          VITE_F_MEASUREMENT_ID: ${{ secrets.VITE_F_MEASUREMENT_ID }}

      # Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
